<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AutoBingSearch.Core\AutoBingSearch.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>AutoBingSearch</AssemblyName>
    <ApplicationIcon>Assets\app-icon.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Assets\app-icon.ico" />
    <None Include="Assets\app-icon.svg" />
  </ItemGroup>

</Project>
